### PR TITLE
DO NOT MERGE: check removal of booster parent

### PR DESCRIPTION
**Pull request by metacosm**
This is a test to see what minimal changes are needed to remove the parent.

### CODE REVIEW

**Comment by gytis** [comment]
I think these things are missing: 
1. Source and output encoding
2. Arquillian cube bom (or we could define separate dependencies in dependencyManagement)
3. IIRC there used to be a plugin to get rid of some warning when running in Eclipse (I've never used it so don't remember for sure)

**Comment by metacosm** [comment]
@gytis yes, this is definitely not the best possible removal version, I just wanted to see what was at least needed :)
We also need to specify explicitly a version for `maven-resources-plugin`… so more work needed.

**Comment by geoand** [comment]
Are we only going to configure the enforcer plugin for the http-secured booster (which is IIRC the only one that uses it)?

**Comment by geoand** [comment]
@gytis Do we need to do anything for the licenses to work properly?

**Comment by gytis** [comment]
@geoand no

**Comment by geoand** [comment]
Cool, thanks!

**Comment by geoand** [comment]
Closing since this has now been done in another PR

**Pull request closed without merging**
